services:
  - type: web
    name: anti-procrastination-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: anti-procrastination-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET  
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-url.netlify.app

databases:
  - name: anti-procrastination-db
    databaseName: anti_procrastination_db
    user: admin
    plan: free
